package com.fmj.fmj.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fmj.fmj.bean.MemberInfo;

import com.fmj.fmj.db.MemberInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberInfoDaoConfig;

    private final MemberInfoDao memberInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberInfoDaoConfig = daoConfigMap.get(MemberInfoDao.class).clone();
        memberInfoDaoConfig.initIdentityScope(type);

        memberInfoDao = new MemberInfoDao(memberInfoDaoConfig, this);

        registerDao(MemberInfo.class, memberInfoDao);
    }
    
    public void clear() {
        memberInfoDaoConfig.clearIdentityScope();
    }

    public MemberInfoDao getMemberInfoDao() {
        return memberInfoDao;
    }

}
